### ISSUE TITLE
May I know where did you get the latest M5 python libraries

### ISSUE THREAD

**Issue by amplatzer** [Sebwap/Sebwap.github.io#1]
And also how did you flash the M5Dial to Micropython firmware, I tried to hold the G0 and power it up , my macOS was not able to find any serial device. 

Thanks in advance.

**Comment by Sebwap** [comment]
You have to press on the button which is on the Stamp S3 while plugin it on your computer.
Then I simply use M5Burner.
I didn't install any specific libraries for this projet, all is included in the last UIflow firmware :)

**Comment by amplatzer** [comment]
> You have to press on the button which is on the Stamp S3 while plugin it on your computer. Then I simply use M5Burner. I didn't install any specific libraries for this projet, all is included in the last UIflow firmware :)

Thanks, I'll try again, I did try to hold the button while plug the power cord, but can't find the device by command lsusb. I'll try the M5Burner. 

OK, it turns out I had a faulty cable, replaced the cable and it's working now , thanks.

**Comment by Sebwap** [comment]
Enjoy this device, and maybe my program !
